name:                dhall-to-jenkins
version:             0.1.0.0
github:              "paulcadman/dhall-to-jenkins"
license:             BSD3
author:              "Paul Cadman"
maintainer:          "pcadman@gmail.com"
copyright:           "Copyright (c) Paul Cadman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/paulcadman/dhall-to-jenkins#readme>

dependencies:
- base >= 4.7 && < 5
- dhall
- insert-ordered-containers
- text
- prettyprinter

library:
  source-dirs: src

executables:
  dhall-to-jenkins-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dhall-to-jenkins

tests:
  dhall-to-jenkins-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dhall-to-jenkins
    - bytestring
    - filepath
    - tasty
    - tasty-golden
    - text
